version: '3'

services:
  api:
    command: npm start
    restart: always
    expose:
      - 80
    environment: 
      - PORT=80
      - NODE_ENV=production
    networks: 
      - "traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.garage-api-secure.rule=Host(`api.garageisep.com`)"
      - "traefik.http.routers.garage-api-secure.entrypoints=websecure"
      - "traefik.http.routers.garage-api-secure.tls.certresolver=myhttpchallenge"
      # https redirection
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.garage-api.rule=Host(`api.garageisep.com`)"
      - "traefik.http.routers.garage-api.entrypoints=web"
      - "traefik.http.routers.garage-api.middlewares=redirect"

networks:
  traefik:
    external: true
